export const GET_CHAT_HISTORY_REQUEST = "GET_CHAT_HISTORY_REQUEST";
export const GET_CHAT_HISTORY_SUCCESS = "GET_CHAT_HISTORY_SUCCESS";
export const GET_CHAT_HISTORY_FAILURE = "GET_CHAT_HISTORY_FAILURE";