export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';


export const UPDATE_PAGE = "UPDATE_PAGE";

export const UPDATE_ITEMS = "UPDATE_ITEMS";

export const CREATE_ITEM = "CREATE_ITEM";

export const DELETE_ITEM = "DELETE_ITEM";

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";