export const FETCH_ITEMS_REQUEST = "FETCH_ITEMS_REQUEST";
export const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";
export const FETCH_ITEMS_FAILURE = "FETCH_ITEMS_FAILURE";

export const UPDATE_PAGE = "UPDATE_PAGE";

export const UPDATE_ITEMS = "UPDATE_ITEMS";

export const CREATE_ITEM = "CREATE_ITEM";

export const DELETE_ITEM = "DELETE_ITEM";

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";

export const CLEAR_LIST = "CLEAR_LIST";

export const GET_DASHBOARD_COUNT_REQUEST = "GET_DASHBOARD_COUNT_REQUEST";
export const GET_DASHBOARD_COUNT_SUCCESS = "GET_DASHBOARD_COUNT_SUCCESS";
export const GET_DASHBOARD_COUNT_FAILURE = "GET_DASHBOARD_COUNT_FAILURE";

export const UPDATE_DASHBOARD_COUNT = "UPDATE_DASHBOARD_COUNT";

export const GET_USER_NOTIFICATIONS_REQUEST = "GET_USER_NOTIFICATIONS_REQUEST";
export const GET_USER_NOTIFICATIONS_SUCCESS = "GET_USER_NOTIFICATIONS_SUCCESS";
export const GET_USER_NOTIFICATIONS_FAILURE = "GET_USER_NOTIFICATIONS_FAILURE";

export const UPDATE_NOTIFICATION_SEEN_REQUEST =
  "UPDATE_NOTIFICATION_SEEN_REQUEST";
export const UPDATE_NOTIFICATION_SEEN_SUCCESS =
  "UPDATE_NOTIFICATION_SEEN_SUCCESS";
export const UPDATE_NOTIFICATION_SEEN_FAILURE =
  "UPDATE_NOTIFICATION_SEEN_FAILURE";

export const DELETE_NOTIFICATION_REQUEST = "DELETE_NOTIFICATION_REQUEST";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_FAILURE = "DELETE_NOTIFICATION_FAILURE";

export const PROFILE_SEARCH_REQUEST = "PROFILE_SEARCH_REQUEST";
export const PROFILE_SEARCH_SUCCESS = "PROFILE_SEARCH_SUCCESS";
export const PROFILE_SEARCH_FAILURE = "PROFILE_SEARCH_FAILURE";

export const GET_ACCOUNT_DETAILS_REQUEST = "GET_ACCOUNT_DETAILS_REQUEST";
export const GET_ACCOUNT_DETAILS_SUCCESS = "GET_ACCOUNT_DETAILS_SUCCESS";
export const GET_ACCOUNT_DETAILS_FAILURE = "GET_ACCOUNT_DETAILS_FAILURE";

export const UPDATE_PROFILE_IMAGE_REQUEST = "UPDATE_PROFILE_IMAGE_REQUEST";
export const UPDATE_PROFILE_IMAGE_SUCCESS = "UPDATE_PROFILE_IMAGE_SUCCESS";
export const UPDATE_PROFILE_IMAGE_FAILURE = "UPDATE_PROFILE_IMAGE_FAILURE";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";

export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const BLOCK_USER_REQUEST = "BLOCK_USER_REQUEST";
export const BLOCK_USER_SUCCESS = "BLOCK_USER_SUCCESS";
export const BLOCK_USER_FAILURE = "BLOCK_USER_FAILURE";

export const UNBLOCK_USER_REQUEST = "UNBLOCK_USER_REQUEST";
export const UNBLOCK_USER_SUCCESS = "UNBLOCK_USER_SUCCESS";
export const UNBLOCK_USER_FAILURE = "UNBLOCK_USER_FAILURE";

export const UPDATE_FCM_REQUEST = "UPDATE_FCM_REQUEST";
export const UPDATE_FCM_SUCCESS = "UPDATE_FCM_SUCCESS";
export const UPDATE_FCM_FAILURE = "UPDATE_FCM_FAILURE";

export const GET_FOLLOWER_DASHBOARD_REQUEST = "GET_FOLLOWER_DASHBOARD_REQUEST";
export const GET_FOLLOWER_DASHBOARD_SUCCESS = "GET_FOLLOWER_DASHBOARD_SUCCESS";
export const GET_FOLLOWER_DASHBOARD_FAILURE = "GET_FOLLOWER_DASHBOARD_FAILURE";

export const GET_FRIEND_DASHBOARD_REQUEST = "GET_FRIEND_DASHBOARD_REQUEST";
export const GET_FRIEND_DASHBOARD_SUCCESS = "GET_FRIEND_DASHBOARD_SUCCESS";
export const GET_FRIEND_DASHBOARD_FAILURE = "GET_FRIEND_DASHBOARD_FAILURE";

export const SELECT_CHAT_USER = "SELECT_CHAT_USER";

export const UPDATE_DASHBOAD_ONLINE_STATUS = "UPDATE_DASHBOAD_ONLINE_STATUS";
