export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE"

export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAILURE = "GET_COMMENTS_FAILURE"

export const GET_REPLIES_REQUEST = "GET_REPLIES_REQUEST";
export const GET_REPLIES_SUCCESS = "GET_REPLIES_SUCCESS";
export const GET_REPLIES_FAILURE = "GET_REPLIES_FAILURE"


export const CREATE_REPLY_REQUEST = "CREATE_REPLY_REQUEST";
export const CREATE_REPLY_SUCCESS = "CREATE_REPLY_SUCCESS";
export const CREATE_REPLY_FAILURE = "CREATE_REPLY_FAILURE"

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE"

export const DELETE_REPLY_REQUEST = "DELETE_REPLY_REQUEST";
export const DELETE_REPLY_SUCCESS = "DELETE_REPLY_SUCCESS";
export const DELETE_REPLY_FAILURE = "DELETE_REPLY_FAILURE"