export const GET_FOLLOWERS_REQUEST = "GET_FOLLOWERS_REQUEST";
export const GET_FOLLOWERS_SUCCESS = "GET_FOLLOWERS_SUCCESS";
export const GET_FOLLOWERS_FAILURE = "GET_FOLLOWERS_FAILURE"

export const GET_FRIEND_REQUEST = "GET_FRIEND_REQUEST";
export const GET_FRIEND_SUCCESS = "GET_FRIEND_SUCCESS";
export const GET_FRIEND_FAILURE = "GET_FRIEND_FAILURE"

export const GET_FOLLOWERS_PENDING_REQUEST = "GET_FOLLOWERS_PENDING_REQUEST";
export const GET_FOLLOWERS_PENDING_SUCCESS = "GET_FOLLOWERS_PENDING_SUCCESS";
export const GET_FOLLOWERS_PENDING_FAILURE = "GET_FOLLOWERS_PENDING_FAILURE"


export const REMOVE_FOLLOWER_REQUEST = "REMOVE_FOLLOWER_REQUEST";
export const REMOVE_FOLLOWER_SUCCESS = "REMOVE_FOLLOWER_SUCCESS";
export const REMOVE_FOLLOWER_FAILURE = "REMOVE_FOLLOWER_FAILURE"

export const ADD_FRIEND_REQUEST = "ADD_FRIEND_REQUEST";
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const ADD_FRIEND_FAILURE = "ADD_FRIEND_FAILURE"