export const GET_FOLLOWERS_REQUEST = "GET_FOLLOWERS_REQUEST";
export const GET_FOLLOWERS_SUCCESS = "GET_FOLLOWERS_SUCCESS";
export const GET_FOLLOWERS_FAILURE = "GET_FOLLOWERS_FAILURE"

export const GET_FRIEND_REQUEST = "GET_FRIEND_REQUEST";
export const GET_FRIEND_SUCCESS = "GET_FRIEND_SUCCESS";
export const GET_FRIEND_FAILURE = "GET_FRIEND_FAILURE"

export const GET_FOLLOWERS_PENDING_REQUEST = "GET_FOLLOWERS_PENDING_REQUEST";
export const GET_FOLLOWERS_PENDING_SUCCESS = "GET_FOLLOWERS_PENDING_SUCCESS";
export const GET_FOLLOWERS_PENDING_FAILURE = "GET_FOLLOWERS_PENDING_FAILURE"


export const REMOVE_FOLLOWER_REQUEST = "REMOVE_FOLLOWER_REQUEST";
export const REMOVE_FOLLOWER_SUCCESS = "REMOVE_FOLLOWER_SUCCESS";
export const REMOVE_FOLLOWER_FAILURE = "REMOVE_FOLLOWER_FAILURE"

export const CONFIRM_FRIEND_REQUEST = "CONFIRM_FRIEND_REQUEST";
export const CONFIRM_FRIEND_SUCCESS = "CONFIRM_FRIEND_SUCCESS";
export const CONFIRM_FRIEND_FAILURE = "CONFIRM_FRIEND_FAILURE"

export const DELETE_FOLLOW_REQUEST_REQUEST = "DELETE_FOLLOW_REQUEST_REQUEST";
export const DELETE_FOLLOW_REQUEST_SUCCESS = "DELETE_FOLLOW_REQUEST_SUCCESS";
export const DELETE_FOLLOW_REQUEST_FAILURE = "DELETE_FOLLOW_REQUEST_FAILURE"

export const CONFIRM_FOLLOW_REQUEST_REQUEST = "CONFIRM_FOLLOW_REQUEST_REQUEST";
export const CONFIRM_FOLLOW_REQUEST_SUCCESS = "CONFIRM_FOLLOW_REQUEST_SUCCESS";
export const CONFIRM_FOLLOW_REQUEST_FAILURE = "CONFIRM_FOLLOW_REQUEST_FAILURE"

export const REMOVE_FRIEND_REQUEST = "REMOVE_FRIEND_REQUEST";
export const REMOVE_FRIEND_SUCCESS = "REMOVE_FRIEND_SUCCESS";
export const REMOVE_FRIEND_FAILURE = "REMOVE_FRIEND_FAILURE"

export const GET_FOLLOW_COUNT_REQUEST = "GET_FOLLOW_COUNT_REQUEST"
export const GET_FOLLOW_COUNT_SUCCESS = "GET_FOLLOW_COUNT_SUCCESS"
export const GET_FOLLOW_COUNT_FAILURE = "GET_FOLLOW_COUNT_FAILURE"

export const GET_FOLLOW_USER_DETAIL_REQUEST = "GET_FOLLOW_USER_DETAIL_REQUEST";
export const GET_FOLLOW_USER_DETAIL_SUCCESS = "GET_FOLLOW_USER_DETAIL_SUCCESS";
export const GET_FOLLOW_USER_DETAIL_FAILURE = "GET_FOLLOW_USER_DETAIL_FAILURE"

export const ADD_FOLLOW_REQUEST_REQUEST = "ADD_FOLLOW_REQUEST_REQUEST";
export const ADD_FOLLOW_REQUEST_SUCCESS = "ADD_FOLLOW_SUCCESS";
export const ADD_FOLLOW_REQUEST_FAILURE = "ADD_FOLLOW_FAILURE"