export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";

export const CREATE_POSTS_REQUEST = "CREATE_POSTS_REQUEST";
export const CREATE_POSTS_SUCCESS = "CREATE_POSTS_SUCCESS";
export const CREATE_POSTS_FAILURE = "CREATE_POSTS_FAILURE";

export const UPDATE_POST_LIKE_REQUEST = "UPDATE_POST_LIKE_REQUEST";
export const UPDATE_POST_LIKE_SUCCESS = "UPDATE_POST_LIKE_SUCCESS";
export const UPDATE_POST_LIKE_FAILURE = "UPDATE_POST_LIKE_FAILURE";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE"